#include "DFGOutput.h"

#include "Assert.h"

#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstring>
#include <string>

namespace FilterFitter
{
    //-------------------------------------------------------------------------

    static uint32_t GetPayloadBytes( DFGTable const& table )
    {
        uint32_t const texelBytes = DFGChannelCount * 2u;

        return table.GetResolution() * table.GetResolution() * texelBytes;
    }

    //-------------------------------------------------------------------------

    void FormatDFGTableBinary( DFGTable const& table, std::vector<uint8_t>& bytes )
    {
        FF_ASSERT( table.GetResolution() > 0 );

        uint32_t const resolution = table.GetResolution();
        uint32_t const payloadBytes = GetPayloadBytes( table );

        DFGBinaryHeader header = {};

        header.m_magic = DFGBinaryMagic;
        header.m_version = DFGBinaryVersion;
        header.m_resolution = resolution;
        header.m_sampleCount = table.GetSampleCount();
        header.m_valuesPerTexel = DFGChannelCount;
        header.m_valueFormat = DFGValueHalf;
        header.m_payloadOffset = static_cast<uint32_t>( sizeof( DFGBinaryHeader ) );
        header.m_payloadBytes = payloadBytes;

        std::snprintf( header.m_name, sizeof( header.m_name ), "%s", DFGTableName );

        bytes.assign( sizeof( DFGBinaryHeader ) + payloadBytes, 0 );

        std::memcpy( bytes.data(), &header, sizeof( header ) );

        uint8_t* const pPayload = bytes.data() + header.m_payloadOffset;

        for ( uint32_t row = 0; row < resolution; ++row )
        {
            for ( uint32_t column = 0; column < resolution; ++column )
            {
                DFGHalfTexel texel;
                GetHalfTexel( table, column, row, texel );

                size_t const offset = ( static_cast<size_t>( row ) * resolution + column ) * 4u;

                std::memcpy( pPayload + offset, &texel.m_scale, sizeof( texel.m_scale ) );
                std::memcpy( pPayload + offset + 2u, &texel.m_bias, sizeof( texel.m_bias ) );
            }
        }
    }

    //-------------------------------------------------------------------------

    static bool WriteFile( void const* pData, size_t size, char const* pPath )
    {
        FF_ASSERT( pPath != nullptr );

        std::FILE* pFile = std::fopen( pPath, "wb" );

        if ( pFile == nullptr )
        {
            return false;
        }

        bool written = ( std::fwrite( pData, 1, size, pFile ) == size );

        // Reported rather than ignored: a full disk can fail at either call, and a silent half-written file embeds as a plausible table of zeroes.
        written = written && ( std::fclose( pFile ) == 0 );

        return written;
    }

    //-------------------------------------------------------------------------

    bool WriteDFGTableBinary( DFGTable const& table, char const* pPath )
    {
        std::vector<uint8_t> bytes;
        FormatDFGTableBinary( table, bytes );

        return WriteFile( bytes.data(), bytes.size(), pPath );
    }

    //-------------------------------------------------------------------------

    void FormatDFGTableHeader( DFGTable const& table, std::vector<char>& text )
    {
        uint32_t const resolution = table.GetResolution();

        char line[512] = {};

        text.clear();

        auto append = [&text] ( char const* pText )
        {
            text.insert( text.end(), pText, pText + std::strlen( pText ) );
        };

        append( "//  Generated by EsotericaFilterFitter. Do not edit.\n" );
        append( "//-------------------------------------------------------------------------\n" );
        append( "//\n" );
        append( "//  Preintegrated split-sum DFG term, one row per roughness and one column per\n" );
        append( "//  N dot V, both sampled at the texel centre.\n" );
        append( "//\n" );
        append( "//  The integral is the engine's own: alpha = roughness squared, k = roughness / 2,\n" );
        append( "//  and the half-vector sampled from the NDF.\n" );
        append( "//\n" );

        std::snprintf( line, sizeof( line ), "//  Grid         : %u x %u texels, %u samples per texel\n", resolution, resolution, table.GetSampleCount() );
        append( line );

        std::snprintf( line, sizeof( line ), "//  Texel centre : N dot V = ( x + 0.5 ) / %u, roughness = ( y + 0.5 ) / %u\n", resolution, resolution );
        append( line );

        append( "//  Row order    : roughness rises with y, so row 0 is the smoothest\n" );
        append( "//  Column order : N dot V rises with x\n" );
        append( "//\n" );
        append( "//  Binary       : FGDF, version 2, a 64-byte header then the payload\n" );
        append( "//  Header       : magic, version, resolution, samples, two values per texel,\n" );
        append( "//                 format 0, payload offset 64, payload bytes, name, reserved\n" );
        append( "//  Payload      : row major, then texel, then channel. ONE TEXEL IS TWO\n" );
        append( "//                 CHANNELS, binary16: channel zero is scale, channel one is\n" );
        append( "//                 bias, which is the engine's RG16 render target. Size is\n" );
        append( "//                 resolution * resolution * 4 bytes.\n" );
        append( "//\n" );
        append( "//  The values below are the payload texel by texel in that order, as the\n" );
        append( "//  uint16 bit patterns the file holds, so this header and the binary carry\n" );
        append( "//  the same numbers and either can be checked against the other.\n" );
        append( "//-------------------------------------------------------------------------\n" );

        std::snprintf( line, sizeof( line ), "static const uint16_t dfg[%u][%u][2] =\n{\n", resolution, resolution );
        append( line );

        for ( uint32_t row = 0; row < resolution; ++row )
        {
            append( "    {\n" );

            for ( uint32_t column = 0; column < resolution; ++column )
            {
                DFGHalfTexel texel;
                GetHalfTexel( table, column, row, texel );

                std::snprintf( line, sizeof( line ), "        { 0x%04X, 0x%04X },\n", texel.m_scale, texel.m_bias );
                append( line );
            }

            append( "    },\n" );
        }

        append( "};\n" );
    }

    //-------------------------------------------------------------------------

    bool WriteDFGTableHeader( DFGTable const& table, char const* pPath )
    {
        std::vector<char> text;
        FormatDFGTableHeader( table, text );

        return WriteFile( text.data(), text.size(), pPath );
    }

    //  Reading the binary back
    //-------------------------------------------------------------------------

    static bool ParseDFGBinary( std::vector<uint8_t> const& bytes, DFGTable const& table, std::vector<float>& values, char* pMessage, size_t messageSize )
    {
        if ( bytes.size() < sizeof( DFGBinaryHeader ) )
        {
            std::snprintf( pMessage, messageSize, "shorter than a header" );
            return false;
        }

        DFGBinaryHeader header = {};
        std::memcpy( &header, bytes.data(), sizeof( header ) );

        if ( header.m_magic != DFGBinaryMagic )
        {
            std::snprintf( pMessage, messageSize, "magic is 0x%08X", header.m_magic );
            return false;
        }

        if ( header.m_version != DFGBinaryVersion )
        {
            std::snprintf( pMessage, messageSize, "version %u, expected %u", header.m_version, DFGBinaryVersion );
            return false;
        }

        // The fields describe a file, so a file whose own fields disagree is refused before anything is allocated from one of them.
        if ( ( header.m_resolution == 0 )
          || ( header.m_valuesPerTexel != DFGChannelCount )
          || ( ( header.m_valueFormat != DFGValueHalf ) && ( header.m_valueFormat != DFGValueFloat ) )
          || ( header.m_payloadOffset != static_cast<uint32_t>( sizeof( DFGBinaryHeader ) ) ) )
        {
            std::snprintf( pMessage, messageSize, "header fields disagree with each other" );
            return false;
        }

        uint32_t const channelBytes = ( header.m_valueFormat == DFGValueHalf ) ? 2u : 4u;
        uint64_t const expectedPayload = static_cast<uint64_t>( header.m_resolution ) * header.m_resolution * DFGChannelCount * channelBytes;

        if ( static_cast<uint64_t>( header.m_payloadBytes ) != expectedPayload )
        {
            std::snprintf( pMessage, messageSize, "payload is %u bytes, the grid says %llu", header.m_payloadBytes, static_cast<unsigned long long>( expectedPayload ) );
            return false;
        }

        if ( ( static_cast<uint64_t>( header.m_payloadOffset ) + header.m_payloadBytes ) != bytes.size() )
        {
            std::snprintf( pMessage, messageSize, "payload is %u bytes at %u, file is %zu", header.m_payloadBytes, header.m_payloadOffset, bytes.size() );
            return false;
        }

        if ( std::memchr( header.m_name, '\0', sizeof( header.m_name ) ) == nullptr )
        {
            std::snprintf( pMessage, messageSize, "name is not terminated" );
            return false;
        }

        //---------------------------------------------------------------------

        if ( header.m_resolution != table.GetResolution() )
        {
            std::snprintf( pMessage, messageSize, "resolution is %u, expected %u", header.m_resolution, table.GetResolution() );
            return false;
        }

        if ( std::strcmp( header.m_name, DFGTableName ) != 0 )
        {
            std::snprintf( pMessage, messageSize, "name is '%s', expected '%s'", header.m_name, DFGTableName );
            return false;
        }

        values.assign( static_cast<size_t>( header.m_resolution ) * header.m_resolution * DFGChannelCount, 0.0F );

        uint8_t const* pPayload = bytes.data() + header.m_payloadOffset;

        for ( size_t index = 0; index < values.size(); ++index )
        {
            if ( header.m_valueFormat == DFGValueHalf )
            {
                uint16_t encoded = 0;
                std::memcpy( &encoded, pPayload + ( index * 2u ), sizeof( encoded ) );

                values[index] = HalfToFloat( encoded );
            }
            else
            {
                float encoded = 0.0F;
                std::memcpy( &encoded, pPayload + ( index * 4u ), sizeof( encoded ) );

                values[index] = encoded;
            }
        }

        return true;
    }

    //-------------------------------------------------------------------------

    static bool ExpectRejected( std::vector<uint8_t> const& corrupt, DFGTable const& table, char const* pCase, char* pMessage, size_t messageSize )
    {
        std::vector<float> values;
        char reason[128] = {};

        bool const accepted = ParseDFGBinary( corrupt, table, values, reason, sizeof( reason ) );

        if ( !accepted )
        {
            std::printf( "    %-30s rejected: %s\n", pCase, reason );
            return true;
        }

        std::printf( "    %-30s ACCEPTED, and should not have been\n", pCase );
        std::snprintf( pMessage, messageSize, "%s was accepted", pCase );

        return false;
    }

    //-------------------------------------------------------------------------

    bool RunDFGWriterSelfCheck()
    {
        bool passed = true;

        std::printf( "\n" );
        std::printf( "dfg table writer\n" );
        std::printf( "  a small grid, both encodings, read back and compared\n" );

        // A grid small enough to fill by hand and varied enough that a misordered axis shows.
        // Every value is distinct, so no two texels can be confused for each other and no channel can be mistaken for the other channel.
        uint32_t const resolution = 4;

        DFGTable table;
        table.m_resolution = resolution;
        table.m_sampleCount = DFGDefaultSampleCount;
        table.m_texels.assign( static_cast<size_t>( resolution ) * resolution, DFGTexel() );

        for ( uint32_t row = 0; row < resolution; ++row )
        {
            for ( uint32_t column = 0; column < resolution; ++column )
            {
                DFGTexel texel;
                texel.m_scale = ( static_cast<double>( row ) + 0.125 ) * 0.25;
                texel.m_bias = ( static_cast<double>( column ) + 0.375 ) * 0.0625;

                table.SetTexel( column, row, texel );
            }
        }

        std::vector<uint8_t> bytes;
        FormatDFGTableBinary( table, bytes );

        bool const sizeOk = ( bytes.size() == ( sizeof( DFGBinaryHeader ) + ( resolution * resolution * 4u ) ) );

        std::vector<float> values;
        char               message[128] = {};

        bool const parsed = ParseDFGBinary( bytes, table, values, message, sizeof( message ) );
        bool const countOk = parsed && ( values.size() == ( static_cast<size_t>( resolution ) * resolution * DFGChannelCount ) );

        // Every stored value has to be the encoding of what went in, in the payload's order, so a transposed axis or a swapped channel fails here.
        bool valuesOk = countOk;

        if ( countOk )
        {
            for ( uint32_t row = 0; ( row < resolution ) && valuesOk; ++row )
            {
                for ( uint32_t column = 0; ( column < resolution ) && valuesOk; ++column )
                {
                    DFGHalfTexel half;
                    GetHalfTexel( table, column, row, half );

                    size_t const index = ( ( static_cast<size_t>( row ) * resolution ) + column ) * DFGChannelCount;

                    if ( ( values[index] != HalfToFloat( half.m_scale ) ) || ( values[index + 1u] != HalfToFloat( half.m_bias ) ) )
                    {
                        valuesOk = false;
                    }
                }
            }
        }

        // The text and the binary are two encodings of one table, so they are compared against each other rather than each against the table separately.
        std::vector<char> text;
        FormatDFGTableHeader( table, text );

        std::string textString( text.begin(), text.end() );

        uint32_t textEntries = 0;
        bool textOk = true;

        for ( size_t position = 0; ( position = textString.find( "{ 0x", position ) ) != std::string::npos; )
        {
            position += 2;

            unsigned int scaleBits = 0;
            unsigned int biasBits = 0;

            if ( std::sscanf( textString.c_str() + position, "%x, 0x%x", &scaleBits, &biasBits ) != 2 )
            {
                textOk = false;
                break;
            }

            uint32_t const row = textEntries / resolution;
            uint32_t const column = textEntries % resolution;

            DFGHalfTexel half;
            GetHalfTexel( table, column, row, half );

            if ( ( static_cast<uint16_t>( scaleBits ) != half.m_scale ) || ( static_cast<uint16_t>( biasBits ) != half.m_bias ) )
            {
                textOk = false;
            }

            ++textEntries;
        }

        textOk = textOk && ( textEntries == ( resolution * resolution ) );

        bool const ok = sizeOk && parsed && valuesOk && textOk;

        passed = passed && ok;

        std::printf( "\n" );
        std::printf( "  %-36s : %s (%zu bytes)\n", "header plus payload size", sizeOk ? "PASS" : "FAIL", bytes.size() );
        std::printf( "  %-36s : %s\n", "binary reads back", ( parsed && countOk ) ? "PASS" : "FAIL" );
        std::printf( "  %-36s : %s\n", "every stored texel survived", valuesOk ? "PASS" : "FAIL" );
        std::printf( "  %-36s : %s (%u texels)\n", "text and binary carry the same numbers", textOk ? "PASS" : "FAIL", textEntries );

        if ( !parsed )
        {
            std::printf( "    binary: %s\n", message );
        }

        // A blob whose fields contradict each other, or a blob that is not this table.
        {
            std::printf( "\n  a blob that parses, with one field changed, must be refused\n" );

            bool rejected = true;

            {
                std::vector<uint8_t> corrupt = bytes;
                uint32_t const badMagic = 0xDEADBEEFu;
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_magic ), &badMagic, sizeof( badMagic ) );
                rejected = ExpectRejected( corrupt, table, "bad magic", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                uint32_t const badVersion = DFGBinaryVersion + 1u;
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_version ), &badVersion, sizeof( badVersion ) );
                rejected = ExpectRejected( corrupt, table, "wrong version", message, sizeof( message ) ) && rejected;
            }

            {
                // A resolution that does not go with the payload length, which is what a reader sizing a texture from the file would allocate against.
                std::vector<uint8_t> corrupt = bytes;
                uint32_t const badResolution = resolution + 1u;
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_resolution ), &badResolution, sizeof( badResolution ) );
                rejected = ExpectRejected( corrupt, table, "resolution against payload", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                uint32_t const badValues = 4u;
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_valuesPerTexel ), &badValues, sizeof( badValues ) );
                rejected = ExpectRejected( corrupt, table, "wrong channel count", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                uint32_t const badOffset = static_cast<uint32_t>( sizeof( DFGBinaryHeader ) ) + 4u;
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_payloadOffset ), &badOffset, sizeof( badOffset ) );
                rejected = ExpectRejected( corrupt, table, "payload offset", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                std::memset( corrupt.data() + offsetof( DFGBinaryHeader, m_name ), 'A', sizeof( DFGBinaryHeader::m_name ) );
                rejected = ExpectRejected( corrupt, table, "unterminated name", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                std::memset( corrupt.data() + offsetof( DFGBinaryHeader, m_name ), 0, sizeof( DFGBinaryHeader::m_name ) );
                std::memcpy( corrupt.data() + offsetof( DFGBinaryHeader, m_name ), "somethingelse", 13 );
                rejected = ExpectRejected( corrupt, table, "another table's name", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                corrupt.resize( bytes.size() - 4u );
                rejected = ExpectRejected( corrupt, table, "short payload", message, sizeof( message ) ) && rejected;
            }

            passed = passed && rejected;
        }

        // The half float conversion, against values whose encodings are known, and against itself over a range wide enough to cross every branch it has.
        {
            struct HalfCase
            {
                float       m_value;
                uint16_t    m_expected;
            };

            HalfCase const cases[] =
            {
                { 0.0F,         0x0000u },
                { 1.0F,         0x3C00u },
                { 0.5F,         0x3800u },
                { 2.0F,         0x4000u },
                { -1.0F,        0xBC00u },
                { 65504.0F,     0x7BFFu },
                { 6.1035156e-5F, 0x0400u },   // the smallest normal half
                { 5.9604645e-8F, 0x0001u },   // the smallest subnormal half
                { 0.33325195F,  0x3555u },
            };

            uint32_t const numCases = static_cast<uint32_t>( sizeof( cases ) / sizeof( cases[0] ) );
            bool casesOk = true;
            bool roundTripOk = true;

            for ( uint32_t index = 0; index < numCases; ++index )
            {
                uint16_t const encoded = FloatToHalf( cases[index].m_value );

                if ( encoded != cases[index].m_expected )
                {
                    std::printf( "    half: %.9g encoded 0x%04X, expected 0x%04X\n", cases[index].m_value, encoded, cases[index].m_expected );
                    casesOk = false;
                }
            }

            // Every half decodes to a float, and encoding that float returns the same half.
            // A half that is its own round trip through both directions is the strongest statement this encoding has without a reference library.
            //
            // It is not, on its own, enough: every float a half decodes to has zero in the bits the encoding drops, so this never exercises a rounding.
            // The loop after it does, over values whose dropped bits are not zero.
            for ( uint32_t bits = 0; bits < 0x10000u; ++bits )
            {
                uint16_t const encoded = static_cast<uint16_t>( bits );

                if ( ( ( encoded >> 10 ) & 0x1Fu ) == 0x1Fu )
                {
                    continue;
                }

                float const value = HalfToFloat( encoded );

                if ( FloatToHalf( value ) != encoded )
                {
                    std::printf( "    half: 0x%04X round trips to 0x%04X\n", encoded, FloatToHalf( value ) );
                    roundTripOk = false;
                    break;
                }
            }

            // Rounding, over values that need it.
            // A normal half keeps eleven significand bits, so nothing it stores is more than one part in 1024 from the value it was given, and a value that comes back further off than that was encoded wrongly whatever the bit pattern looks like.
            // The sweep stops below the largest finite half, where the infinity above it is the answer rather than an error.
            bool roundingOk = true;

            for ( uint32_t bits = 0x39000000u; ( bits < 0x477F0000u ) && roundingOk; bits += 7919u )
            {
                float value = 0.0F;
                std::memcpy( &value, &bits, sizeof( value ) );

                float const stored = HalfToFloat( FloatToHalf( value ) );
                double const relative = std::fabs( ( static_cast<double>( stored ) - value ) / value );

                if ( relative > 1.2e-3 )
                {
                    std::printf( "    half: %.9g encoded as %.9g, a relative error of %.6e\n", value, stored, relative );
                    roundingOk = false;
                }
            }

            std::printf( "\n" );
            std::printf( "  %-36s : %s\n", "half encoding against known values", casesOk ? "PASS" : "FAIL" );
            std::printf( "  %-36s : %s\n", "half round trip over every encoding", roundTripOk ? "PASS" : "FAIL" );
            std::printf( "  %-36s : %s\n", "half rounds to within one part in 1024", roundingOk ? "PASS" : "FAIL" );

            passed = passed && casesOk && roundTripOk && roundingOk;
        }

        return passed;
    }
}
