#include "Assert.h"
#include "ProfileGGX.h"
#include "TableWriter.h"
#include "TetrahedralProjection.h"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

namespace FilterFitter
{
    //  Formatting
    //-------------------------------------------------------------------------

    // %.9g is FLT_DECIMAL_DIG, the smallest number of significant digits that round-trips EVERY float.
    //
    // %.8g is not enough. It happens to be enough for all four published tables and for the fitted esoterica table, whose 210 values were measured to round-trip, but not in general.
    // The decimal spacing of an eight-digit rendering is 10^(m-7) for a leading digit at 10^m, and a float's ulp can be as small as 2^(e-24) for a value in [2^e, 2^(e+1)); at 0.107421875 the spacing is 1e-8 against an ulp of 7.45e-9, so %.8g renders it 0.10742188, which reads back as a DIFFERENT float.
    // The tetrahedral shape in the check below is what catches this, because its values are the first there that nobody else chose.
    static void AppendLiteral( std::string& text, double value )
    {
        char buffer[64] = {};

        std::snprintf( buffer, sizeof( buffer ), "%.9g", static_cast<float>( value ) );

        text += buffer;
    }

    //-------------------------------------------------------------------------

    static void AppendFloat4List
    (
        std::string& text,
        CoefficientTable const& table,
        uint32_t level,
        uint32_t parameter,
        uint32_t coefficient,
        uint32_t numIndices
    )
    {
        for ( uint32_t index = 0; index < numIndices; ++index )
        {
            text += "float4(";

            for ( uint32_t subTap = 0; subTap < 4; ++subTap )
            {
                AppendLiteral( text, table.GetCoefficient( level, parameter, coefficient, index, subTap ) );

                if ( subTap < 3 )
                {
                    text += ", ";
                }
            }

            text += ")";

            if ( ( index + 1 ) < numIndices )
            {
                text += ", ";
            }
        }
    }

    //-------------------------------------------------------------------------

    // The number of opening braces the emitted body must contain.
    static uint32_t GetExpectedBraceCount( uint32_t numActiveCoefficients )
    {
        uint32_t const perParameter = ( numActiveCoefficients > 1 ) ? ( 1 + numActiveCoefficients ) : 1;

        return 1 + ( CoefficientTable::NumLevels * ( 1 + ( CoefficientTable::NumParameters * perParameter ) ) );
    }

    //-------------------------------------------------------------------------

    void FormatTableHeader( CoefficientTable const& table, std::string& text )
    {
        uint32_t const numIndices = table.GetNumIndices();
        uint32_t const numActive = table.GetActiveCoefficientCount();
        uint32_t const numTaps = table.GetNumTaps();
        uint32_t const numSubTaps = table.GetTapCount();

        char declaration[256] = {};

        if ( numActive > 1 )
        {
            std::snprintf( declaration, sizeof( declaration ), "static const float4 coeffs[%u][%u][%u][%u]", CoefficientTable::NumLevels, CoefficientTable::NumParameters, numActive, numIndices );
        }
        else
        {
            std::snprintf( declaration, sizeof( declaration ), "static const float4 coeffs[%u][%u][%u]", CoefficientTable::NumLevels, CoefficientTable::NumParameters, numIndices );
        }

        char line[512] = {};

        text.clear();

        text += "//  Generated by EsotericaFilterFitter. Do not edit.\n";
        text += "//-------------------------------------------------------------------------\n";
        text += "//\n";

        std::snprintf( line, sizeof( line ), "//  Table       : %s\n", table.GetName() );
        text += line;
        std::snprintf( line, sizeof( line ), "//  Projection  : %s\n", GetProbeMapName( table.GetProjection() ) );
        text += line;
        std::snprintf( line, sizeof( line ), "//  Levels      : %u\n", CoefficientTable::NumLevels );
        text += line;
        std::snprintf( line, sizeof( line ), "//  Parameters  : %u - 0 dir0, 1 dir1, 2 dir2, 3 level, 4 weight\n", CoefficientTable::NumParameters );
        text += line;
        std::snprintf( line, sizeof( line ), "//  Coefficients: %u active%s\n", numActive, ( numActive == 1 ) ? ", a constant table being the quadratic with a1 = a2 = 0" : "" );
        text += line;
        std::snprintf( line, sizeof( line ), "//  Taps        : %u per axis, %u total, %u indices of four sub-taps\n", numTaps, numSubTaps, numIndices );
        text += line;

        // The axis count is the map's, and the sentence that explains it is the map's too.
        // Whichever map this is, the line says where its axes come from and how the index range folds; neither map's answer is the unexplained default of the other's.
        std::snprintf
        (
            line, sizeof( line ), "//  Axes        : %u - %s\n", table.GetNumAxes(),
            ( table.GetProjection() == ProbeMap::Cube )
            ? "one per axis direction, which is the cube's three face normals"
            : "one per symmetry axis of the map, folded into the last extent"
        );
        text += line;
        text += declaration;
        text += " =\n{\n";

        // One line per ( level, parameter ), and per coefficient when the table is quadratic.
        // Trailing commas throughout so that adding or removing the last element of any list produces a one-line difference.
        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            text += "    {\n";

            for ( uint32_t parameter = 0; parameter < CoefficientTable::NumParameters; ++parameter )
            {
                if ( numActive > 1 )
                {
                    text += "        {\n";

                    for ( uint32_t coefficient = 0; coefficient < numActive; ++coefficient )
                    {
                        text += "            { ";
                        AppendFloat4List( text, table, level, parameter, coefficient, numIndices );
                        text += " },\n";
                    }

                    text += "        },\n";
                }
                else
                {
                    text += "        { ";
                    AppendFloat4List( text, table, level, parameter, 0, numIndices );
                    text += " },\n";
                }
            }

            text += "    },\n";
        }

        text += "};\n";
    }

    //-------------------------------------------------------------------------

    bool WriteTableHeader( CoefficientTable const& table, char const* pPath )
    {
        FF_ASSERT( pPath != nullptr );

        std::string text;
        FormatTableHeader( table, text );

        std::FILE* pFile = std::fopen( pPath, "wb" );
        if ( pFile == nullptr )
        {
            return false;
        }

        bool written = ( std::fwrite( text.data(), 1, text.size(), pFile ) == text.size() );

        // Reported rather than ignored: a full disk fails at fclose on some systems and at fwrite on others, and a silent half-written header is worse than a missing one because it still compiles.
        written = written && ( std::fclose( pFile ) == 0 );

        return written;
    }

    //  Binary output
    //-------------------------------------------------------------------------

    void FormatTableBinary
    (
        CoefficientTable const& table,
        char const* pProfileName,
        LevelWidthCurve const& curve,
        std::vector<uint8_t>& bytes
    )
    {
        FF_ASSERT( curve.GetNumLevels() == CoefficientTable::NumLevels );

        uint32_t const numActive = table.GetActiveCoefficientCount();
        uint32_t const numIndices = table.GetNumIndices();

        uint32_t const numFloat4 = CoefficientTable::NumLevels
            * CoefficientTable::NumParameters
            * numActive * numIndices;

        TableBinaryHeader header = {};

        header.m_magic = TableBinaryMagic;
        header.m_version = TableBinaryVersion;
        header.m_numLevels = CoefficientTable::NumLevels;
        header.m_numParameters = CoefficientTable::NumParameters;
        header.m_numActiveCoefficients = numActive;
        header.m_numTapsPerAxis = table.GetNumTaps();
        header.m_projection = static_cast<uint32_t>( table.GetProjection() );
        header.m_numAxes = table.GetNumAxes();
        header.m_numIndices = numIndices;
        header.m_numFloat4 = numFloat4;
        header.m_payloadOffset = static_cast<uint32_t>( sizeof( TableBinaryHeader ) );
        header.m_payloadBytes = numFloat4 * 16;

        std::snprintf( header.m_shapeName, sizeof( header.m_shapeName ), "%s", table.GetName() );
        std::snprintf( header.m_profileName, sizeof( header.m_profileName ), "%s", ( pProfileName != nullptr ) ? pProfileName : "" );

        // The widths are the authority on which curve this table belongs to. Stored as float because the payload is float and a double here would pad the layout.
        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            header.m_widths[level] = static_cast<float>( curve.GetWidth( level ) );
        }

        bytes.assign( sizeof( TableBinaryHeader ) + header.m_payloadBytes, 0 );

        std::memcpy( bytes.data(), &header, sizeof( header ) );

        uint8_t* const pPayload = bytes.data() + header.m_payloadOffset;

        uint32_t cursor = 0;

        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            for ( uint32_t parameter = 0; parameter < CoefficientTable::NumParameters; ++parameter )
            {
                for ( uint32_t coefficient = 0; coefficient < numActive; ++coefficient )
                {
                    for ( uint32_t index = 0; index < numIndices; ++index )
                    {
                        float components[4] = {};

                        for ( uint32_t subTap = 0; subTap < 4; ++subTap )
                        {
                            components[subTap] = static_cast<float>( table.GetCoefficient( level, parameter, coefficient, index, subTap ) );
                        }

                        std::memcpy( pPayload + ( static_cast<size_t>( cursor ) * 16 ), components, sizeof( components ) );
                        ++cursor;
                    }
                }
            }
        }
    }

    //-------------------------------------------------------------------------

    bool WriteTableBinary
    (
        CoefficientTable const& table,
        char const* pProfileName,
        LevelWidthCurve const& curve,
        char const* pPath
    )
    {
        FF_ASSERT( pPath != nullptr );

        std::vector<uint8_t> bytes;
        FormatTableBinary( table, pProfileName, curve, bytes );

        std::FILE* pFile = std::fopen( pPath, "wb" );
        if ( pFile == nullptr )
        {
            return false;
        }

        bool written = ( std::fwrite( bytes.data(), 1, bytes.size(), pFile ) == bytes.size() );

        written = written && ( std::fclose( pFile ) == 0 );

        return written;
    }

    //  Reading the emitted text back
    //-------------------------------------------------------------------------

    static bool ParseFloat4Values( std::string const& text, std::vector<float>& values )
    {
        char const* const pMarker = "float4(";
        size_t const markerLength = 7;

        values.clear();

        char const* const pBase = text.c_str();
        size_t position = 0;

        while ( ( position = text.find( pMarker, position ) ) != std::string::npos )
        {
            position += markerLength;

            for ( uint32_t component = 0; component < 4; ++component )
            {
                char* pEnd = nullptr;
                float const value = std::strtof( pBase + position, &pEnd );

                if ( pEnd == ( pBase + position ) )
                {
                    return false;
                }

                values.push_back( value );
                position = static_cast<size_t>( pEnd - pBase );

                while ( ( position < text.size() ) && ( ( text[position] == ' ' ) || ( text[position] == ',' ) ) )
                {
                    ++position;
                }
            }

            if ( ( position >= text.size() ) || ( text[position] != ')' ) )
            {
                return false;
            }

            ++position;
        }

        return true;
    }

    //-------------------------------------------------------------------------

    static uint32_t CountCharacter( std::string const& text, char character )
    {
        uint32_t count = 0;

        for ( char const value : text )
        {
            if ( value == character )
            {
                ++count;
            }
        }

        return count;
    }

    //  Reading the binary back
    //-------------------------------------------------------------------------

    static bool ParseTableBinary
    (
        std::vector<uint8_t> const& bytes,
        CoefficientTable const& table,
        char const* pProfileName,
        LevelWidthCurve const& curve,
        std::vector<float>& values,
        char* pMessage,
        size_t messageSize
    )
    {
        uint32_t const numActive = table.GetActiveCoefficientCount();
        uint32_t const numIndices = table.GetNumIndices();

        if ( bytes.size() < sizeof( TableBinaryHeader ) )
        {
            std::snprintf( pMessage, messageSize, "shorter than a header" );
            return false;
        }

        TableBinaryHeader header = {};
        std::memcpy( &header, bytes.data(), sizeof( header ) );

        if ( header.m_magic != TableBinaryMagic )
        {
            std::snprintf( pMessage, messageSize, "magic is 0x%08X", header.m_magic );
            return false;
        }

        if ( header.m_version != TableBinaryVersion )
        {
            std::snprintf( pMessage, messageSize, "version %u, expected %u", header.m_version, TableBinaryVersion );
            return false;
        }

        // The map first, and as a value rather than as an enum: it came out of a file, so it can be anything.
        // A version-4 header that says 7 is rejected here rather than cast and used.
        if ( !IsProbeMapValue( header.m_projection ) )
        {
            std::snprintf( pMessage, messageSize, "projection %u names no map", header.m_projection );
            return false;
        }

        // SELF-CONSISTENCY FIRST, table comparison second, and the order is the point.
        // These fields describe a table, so a file whose own fields disagree is not a table that happens to be the wrong one - it is not a table.
        // The checks are therefore live even though every caller here also has a table to compare against, and they are what a reader with NO table to compare against would rely on: the runtime, enumerating what it has.
        //
        //      indices = axes * taps / 4          taps a multiple of four
        //      float4  = levels * parameters * coefficients * indices
        //
        // All of it before the allocation below, which is sized from the file.
        if ( ( header.m_numTapsPerAxis == 0 )
         || ( ( header.m_numTapsPerAxis % 4 ) != 0 )
         || ( header.m_numAxes == 0 )
         || ( GetProbeMapAxisCount( static_cast<ProbeMap>( header.m_projection ) ) != header.m_numAxes )
         || ( header.m_numIndices != ( ( header.m_numAxes * header.m_numTapsPerAxis ) / 4 ) ) )
        {
            std::snprintf( pMessage, messageSize, "shape fields disagree with each other" );
            return false;
        }

        uint64_t const expectedFloat4 = static_cast<uint64_t>( header.m_numLevels )
            * header.m_numParameters
            * header.m_numActiveCoefficients
            * header.m_numIndices;

        if ( static_cast<uint64_t>( header.m_numFloat4 ) != expectedFloat4 )
        {
            std::snprintf( pMessage, messageSize, "numFloat4 is %u, expected %llu", header.m_numFloat4, static_cast<unsigned long long>( expectedFloat4 ) );
            return false;
        }

        // The payload's own size, against the file that actually arrived, before anything is allocated from a field the file supplied.
        if ( ( header.m_payloadOffset % 16 ) != 0 )
        {
            std::snprintf( pMessage, messageSize, "payload offset %u is not 16-byte aligned", header.m_payloadOffset );
            return false;
        }

        if ( header.m_payloadOffset != sizeof( TableBinaryHeader ) )
        {
            std::snprintf( pMessage, messageSize, "payload offset is %u, expected %zu", header.m_payloadOffset, sizeof( TableBinaryHeader ) );
            return false;
        }

        if ( ( static_cast<uint64_t>( header.m_payloadOffset ) + header.m_payloadBytes ) != bytes.size() )
        {
            std::snprintf( pMessage, messageSize, "payload is %u bytes at %u, file is %zu", header.m_payloadBytes, header.m_payloadOffset, bytes.size() );
            return false;
        }

        if ( header.m_payloadBytes != ( header.m_numFloat4 * 16u ) )
        {
            std::snprintf( pMessage, messageSize, "payload is %u bytes, numFloat4 says %u", header.m_payloadBytes, header.m_numFloat4 * 16u );
            return false;
        }

        char const* pEnd = static_cast<char const*>( std::memchr( header.m_shapeName, '\0', sizeof( header.m_shapeName ) ) );
        if ( pEnd == nullptr )
        {
            std::snprintf( pMessage, messageSize, "shape name is not terminated" );
            return false;
        }

        pEnd = static_cast<char const*>( std::memchr( header.m_profileName, '\0', sizeof( header.m_profileName ) ) );
        if ( pEnd == nullptr )
        {
            std::snprintf( pMessage, messageSize, "profile name is not terminated" );
            return false;
        }

        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            if ( !std::isfinite( header.m_widths[level] ) )
            {
                std::snprintf( pMessage, messageSize, "width at level %u is not finite", level );
                return false;
            }
        }

        //---------------------------------------------------------------------

        if ( header.m_projection != static_cast<uint32_t>( table.GetProjection() ) )
        {
            std::snprintf( pMessage, messageSize, "projection is %s, expected %s", GetProbeMapName( static_cast<ProbeMap>( header.m_projection ) ), GetProbeMapName( table.GetProjection() ) );
            return false;
        }

        if ( ( header.m_numLevels != CoefficientTable::NumLevels )
         || ( header.m_numParameters != CoefficientTable::NumParameters )
         || ( header.m_numActiveCoefficients != numActive )
         || ( header.m_numTapsPerAxis != table.GetNumTaps() )
         || ( header.m_numAxes != table.GetNumAxes() )
         || ( header.m_numIndices != numIndices ) )
        {
            std::snprintf( pMessage, messageSize, "shape fields disagree with the table" );
            return false;
        }

        if ( std::strcmp( header.m_shapeName, table.GetName() ) != 0 )
        {
            std::snprintf( pMessage, messageSize, "shape is '%s', expected '%s'", header.m_shapeName, table.GetName() );
            return false;
        }

        if ( std::strcmp( header.m_profileName, ( pProfileName != nullptr ) ? pProfileName : "" ) != 0 )
        {
            std::snprintf( pMessage, messageSize, "profile is '%s', expected '%s'", header.m_profileName, ( pProfileName != nullptr ) ? pProfileName : "" );
            return false;
        }

        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            float const expected = static_cast<float>( curve.GetWidth( level ) );

            if ( header.m_widths[level] != expected )
            {
                std::snprintf( pMessage, messageSize, "width at level %u is %.8g, expected %.8g", level, header.m_widths[level], expected );
                return false;
            }
        }

        values.assign( static_cast<size_t>( header.m_numFloat4 ) * 4, 0.0f );

        std::memcpy( values.data(), bytes.data() + header.m_payloadOffset, header.m_payloadBytes );

        return true;
    }

    //-------------------------------------------------------------------------

    // Requires every value to equal the table's own, cast to float, in the order both encodings emit: level, parameter, coefficient, index, sub-tap.
    // The table is double and both files are float, so the narrowing is the format's own loss and nothing beyond it is allowed.
    static bool CompareValuesWithTable( CoefficientTable const& table, std::vector<float> const& values )
    {
        uint32_t const numActive = table.GetActiveCoefficientCount();
        uint32_t const numIndices = table.GetNumIndices();

        size_t const expected = static_cast<size_t>( CoefficientTable::NumLevels )
            * CoefficientTable::NumParameters
            * numActive * numIndices * 4;

        if ( values.size() != expected )
        {
            return false;
        }

        size_t cursor = 0;

        for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
        {
            for ( uint32_t parameter = 0; parameter < CoefficientTable::NumParameters; ++parameter )
            {
                for ( uint32_t coefficient = 0; coefficient < numActive; ++coefficient )
                {
                    for ( uint32_t index = 0; index < numIndices; ++index )
                    {
                        for ( uint32_t subTap = 0; subTap < 4; ++subTap )
                        {
                            float const source = static_cast<float>( table.GetCoefficient( level, parameter, coefficient, index, subTap ) );

                            if ( values[cursor] != source )
                            {
                                return false;
                            }

                            ++cursor;
                        }
                    }
                }
            }
        }

        return true;
    }

    //-------------------------------------------------------------------------

    static bool ExpectRejected
    (
        std::vector<uint8_t> const& corrupt,
        CoefficientTable const& table,
        char const* pProfileName,
        LevelWidthCurve const& curve,
        char const* pCase,
        char* pMessage,
        size_t messageSize
    )
    {
        std::vector<float> values;
        char reason[128] = {};

        bool const accepted = ParseTableBinary( corrupt, table, pProfileName, curve, values, reason, sizeof( reason ) );

        if ( !accepted )
        {
            std::printf( "    %-28s rejected: %s\n", pCase, reason );
            return true;
        }

        std::printf( "    %-28s ACCEPTED, and should not have been\n", pCase );
        std::snprintf( pMessage, messageSize, "%s was accepted", pCase );

        return false;
    }

    //-------------------------------------------------------------------------

    static void PatchU32( std::vector<uint8_t>& bytes, size_t offset, uint32_t value )
    {
        std::memcpy( bytes.data() + offset, &value, sizeof( value ) );
    }

    //-------------------------------------------------------------------------

    bool RunTableWriterSelfCheck()
    {
        bool passed = true;

        std::printf( "\n" );
        std::printf( "table writer\n" );
        std::printf( "  both encodings of every shape parsed back from their own bytes\n" );
        std::printf( "  the published four are cubemap data; the last row is the same\n" );
        std::printf( "  layout over a tetrahedron's four axes, built rather than loaded\n" );

        ReferenceTable const shapes[] =
        {
            ReferenceTable::Const8,
            ReferenceTable::Const16,
            ReferenceTable::Const32,
            ReferenceTable::Quad32,
        };

        std::string          text;
        std::vector<float>   textValues;
        std::vector<uint8_t> bytes;
        std::vector<float>   binaryValues;
        char                 message[128] = {};

        // What the published tables were fitted for: GGX on the reference's gloss curve.
        // The identity matters here because the binary carries it.
        ProfileGGX const     publishedProfile( LobeConvention::NDFCosineHemisphere );
        LevelWidthCurve const publishedCurve = LevelWidthCurve::MakePaperGloss( ProfileGGX::NumLevels, ProfileGGX::MaxSpecPower );

        std::printf( "\n  %-16s %-14s %-8s %-8s %-8s %-8s %-8s\n", "shape", "binary bytes", "text", "braces", "binary", "header", "result" );

        for ( ReferenceTable shape : shapes )
        {
            CoefficientTable table;
            table.Load( shape );

            // Text. Parsed out of the emitted characters rather than replayed from what went in, because replaying would test nothing.
            FormatTableHeader( table, text );

            bool const textOk = ParseFloat4Values( text, textValues ) && CompareValuesWithTable( table, textValues );

            // The body's nesting has to match the rank it declares. A body that disagrees parses fine and reads fine, and only a compiler notices.
            uint32_t const expectedBraces = GetExpectedBraceCount( table.GetActiveCoefficientCount() );

            bool const bracesOk = ( CountCharacter( text, '{' ) == expectedBraces )
                && ( CountCharacter( text, '}' ) == expectedBraces );

            // Binary
            FormatTableBinary( table, publishedProfile.GetName(), publishedCurve, bytes );

            message[0] = '\0';

            bool const binaryParsed = ParseTableBinary( bytes, table, publishedProfile.GetName(), publishedCurve, binaryValues, message, sizeof( message ) );
            bool const binaryOk = binaryParsed && CompareValuesWithTable( table, binaryValues );

            // The header has to reject what it is not for: a table fitted for one curve, loaded by a runtime selecting with another, produces a plausible image of the wrong width and nothing anywhere reports a problem.
            // Checked against a different curve, a different profile name, and a single perturbed width.
            LevelWidthCurve const otherCurve = LevelWidthCurve::MakeEsotericaLinear( ProfileGGX::NumLevels );

            char                mismatchMessage[128] = {};
            std::vector<float>  mismatchValues;

            bool const rejectsOtherCurve = !ParseTableBinary( bytes, table, publishedProfile.GetName(), otherCurve, mismatchValues, mismatchMessage, sizeof( mismatchMessage ) );

            std::vector<double> nudged = publishedCurve.GetWidths();
            nudged[3] = nudged[3] * 1.01;

            bool const rejectsNudgedCurve = !ParseTableBinary( bytes, table, publishedProfile.GetName(), LevelWidthCurve::MakeExplicit( nudged ), mismatchValues, mismatchMessage, sizeof( mismatchMessage ) );

            bool const rejectsOtherProfile = !ParseTableBinary( bytes, table, "Beckmann (D * cos, hemisphere)", publishedCurve, mismatchValues, mismatchMessage, sizeof( mismatchMessage ) );

            bool const headerOk = rejectsOtherCurve && rejectsNudgedCurve && rejectsOtherProfile;

            bool const ok = textOk && bracesOk && binaryOk && headerOk;

            passed = passed && ok;

            std::printf
            (
                "  %-16s %-14u %-8s %-8s %-8s %-8s %-8s\n",
                GetReferenceTableName( shape ), static_cast<uint32_t>( bytes.size() ),
                textOk ? "ok" : "FAIL",
                bracesOk ? "ok" : "FAIL",
                binaryOk ? "ok" : "FAIL",
                headerOk ? "ok" : "FAIL",
                ok ? "ok" : "FAIL"
            );

            if ( !binaryParsed )
            {
                std::printf( "             binary: %s\n", message );
            }

            if ( !headerOk )
            {
                std::printf
                (
                    "             header must reject a different curve, a nudged width and a different profile; accepted %s%s%s\n",
                    rejectsOtherCurve ? "" : "the other curve ",
                    rejectsNudgedCurve ? "" : "the nudged width ",
                    rejectsOtherProfile ? "" : "the other profile"
                );
            }

            if ( !textOk || !bracesOk )
            {
                std::printf( "             expected %u values and %u of each brace\n", static_cast<uint32_t>( textValues.size() ), expectedBraces );
            }
        }

        // The same layout over a tetrahedron's four axes.
        // There is no published file to load, so the values are a deterministic pattern rather than radiance: what is being checked is the LAYOUT, which is the part a second map changes and the part the runtime reads back.
        {
            CoefficientTable table;
            table.Create( TableShape::ForMap( ProbeMap::Tetrahedron, 8, 1, "tetra_const_8" ) );

            for ( uint32_t level = 0; level < CoefficientTable::NumLevels; ++level )
            {
                for ( uint32_t tap = 0; tap < table.GetTapCount(); ++tap )
                {
                    for ( uint32_t parameter = 0; parameter < CoefficientTable::NumParameters; ++parameter )
                    {
                        double const value = static_cast<double>( ( level * 1000u ) + ( tap * 10u ) + parameter ) / 1024.0;
                        table.SetTapCoefficient( level, tap, parameter, 0, value );
                    }
                }
            }

            bool const shapeOk = table.ValidateShape()
                && ( table.GetNumAxes() == TetrahedralProjection::NumFrames )
                && ( table.GetNumIndices() == ( ( TetrahedralProjection::NumFrames * 8u ) / 4u ) )
                && ( table.GetTapCount() == ( TetrahedralProjection::NumFrames * 8u ) );

            FormatTableHeader( table, text );

            bool const textOk = ParseFloat4Values( text, textValues ) && CompareValuesWithTable( table, textValues );

            uint32_t const expectedBraces = GetExpectedBraceCount( table.GetActiveCoefficientCount() );

            bool const bracesOk = ( CountCharacter( text, '{' ) == expectedBraces ) && ( CountCharacter( text, '}' ) == expectedBraces );

            FormatTableBinary( table, publishedProfile.GetName(), publishedCurve, bytes );

            message[0] = '\0';

            bool const binaryParsed = ParseTableBinary( bytes, table, publishedProfile.GetName(), publishedCurve, binaryValues, message, sizeof( message ) );
            bool const binaryOk = binaryParsed && CompareValuesWithTable( table, binaryValues );

            // A four-axis table and a three-axis one must not be interchangeable, or the axis count would be decoration.
            // Same taps per axis, same level count, and the parse has to refuse the other shape.
            CoefficientTable const cubePeer = [] ()
            {
                CoefficientTable peer;
                peer.Create( TableShape::ForMap( ProbeMap::Cube, 8, 1, "cube_const_8" ) );
                return peer;
            }( );

            char               peerMessage[128] = {};
            std::vector<float> peerValues;

            bool const rejectsAxesMismatch = !ParseTableBinary( bytes, cubePeer, publishedProfile.GetName(), publishedCurve, peerValues, peerMessage, sizeof( peerMessage ) );

            bool const ok = shapeOk && textOk && bracesOk && binaryOk && rejectsAxesMismatch;

            passed = passed && ok;

            std::printf
            (
                "  %-16s %-14u %-8s %-8s %-8s %-8s %-8s\n",
                table.GetName(), static_cast<uint32_t>( bytes.size() ),
                textOk ? "ok" : "FAIL",
                bracesOk ? "ok" : "FAIL",
                binaryOk ? "ok" : "FAIL",
                rejectsAxesMismatch ? "ok" : "FAIL",
                ok ? "ok" : "FAIL"
            );

            if ( !binaryParsed )
            {
                std::printf( "             binary: %s\n", message );
            }

            if ( !textOk || !bracesOk )
            {
                size_t const expectedValues = static_cast<size_t>( CoefficientTable::NumLevels ) * CoefficientTable::NumParameters * table.GetActiveCoefficientCount() * table.GetNumIndices() * 4;

                std::printf( "             text: expected %zu values, parsed %zu, %u of each brace\n", expectedValues, textValues.size(), expectedBraces );

                size_t cursor = 0;
                for ( uint32_t level = 0; ( level < CoefficientTable::NumLevels ) && ( cursor < textValues.size() ); ++level )
                {
                    for ( uint32_t parameter = 0; ( parameter < CoefficientTable::NumParameters ) && ( cursor < textValues.size() ); ++parameter )
                    {
                        for ( uint32_t index = 0; ( index < table.GetNumIndices() ) && ( cursor < textValues.size() ); ++index )
                        {
                            for ( uint32_t subTap = 0; ( subTap < 4 ) && ( cursor < textValues.size() ); ++subTap, ++cursor )
                            {
                                float const source = static_cast<float>( table.GetCoefficient( level, parameter, 0, index, subTap ) );

                                if ( textValues[cursor] != source )
                                {
                                    std::printf( "             first mismatch at %zu: level %u parameter %u index %u subTap %u: table %.9g, parsed %.9g\n", cursor, level, parameter, index, subTap, source, textValues[cursor] );
                                    cursor = textValues.size();
                                    level = CoefficientTable::NumLevels;
                                    parameter = CoefficientTable::NumParameters;
                                }
                            }
                        }
                    }
                }
            }

            if ( !rejectsAxesMismatch )
            {
                std::printf( "             a three-axis table was accepted against a four-axis blob\n" );
            }
        }

        //  A file that nobody vouched for
        //---------------------------------------------------------------------

        {
            std::printf( "\n  a blob that parses, with one field changed, must be refused\n" );

            CoefficientTable table;
            table.Load( ReferenceTable::Const8 );

            FormatTableBinary( table, publishedProfile.GetName(), publishedCurve, bytes );

            bool rejected = true;

            {
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_magic ), 0xDEADBEEF );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "bad magic", message, sizeof( message ) ) && rejected;
            }

            {
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_version ), TableBinaryVersion + 1 );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "wrong version", message, sizeof( message ) ) && rejected;
            }

            {
                // A value that names no map at all. Read as an enum without checking, this is the one that would index a name table out of range.
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_projection ), 7 );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "projection 7 (no map)", message, sizeof( message ) ) && rejected;
            }

            {
                // A valid map that the axis count contradicts. Caught by the self-consistency pass, which is what a reader with no table to compare against depends on.
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_projection ), static_cast<uint32_t>( ProbeMap::Tetrahedron ) );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "axes contradict the map", message, sizeof( message ) ) && rejected;
            }

            {
                // A valid, self-consistent tetrahedral table, parsed against a cubemap one.
                // This is the case the projection field exists for and it cannot be built by patching the published blob: a wrong map implies a different shape, hence a different file length, and the size check refuses before the projection is even looked at.
                CoefficientTable tetraTable;
                tetraTable.Create( TableShape::ForMap( ProbeMap::Tetrahedron, 8, 1, "tetra_const_8" ) );

                std::vector<uint8_t> tetraBytes;
                FormatTableBinary( tetraTable, publishedProfile.GetName(), publishedCurve, tetraBytes );

                CoefficientTable cubePeer;
                cubePeer.Create( TableShape::ForMap( ProbeMap::Cube, 8, 1, "tetra_const_8" ) );

                bool const rejectsWrongMap = ExpectRejected( tetraBytes, cubePeer, publishedProfile.GetName(), publishedCurve, "tetrahedron for a cube table", message, sizeof( message ) );

                rejected = rejectsWrongMap && rejected;
            }

            {
                // A self-consistent shape, claiming a payload longer than the file.
                // A reader that allocated from this before checking would ask for 16 GB; the size check is what it has to reach first.
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_payloadBytes ), 0x40000000u );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "payload longer than file", message, sizeof( message ) ) && rejected;
            }

            {
                // The field that decides how much is allocated, claiming more than the shape can hold. Nothing is allocated before this is checked.
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_numFloat4 ), 0x40000000u );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "numFloat4 larger than shape", message, sizeof( message ) ) && rejected;
            }

            {
                // Self-consistent size, larger than the file. A reader that allocated first and checked second would ask for 16 GB here.
                std::vector<uint8_t> corrupt = bytes;
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_numFloat4 ), 280 );
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_numIndices ), 8 );
                PatchU32( corrupt, offsetof( TableBinaryHeader, m_payloadBytes ), 280 * 16 );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "shape sized past the file", message, sizeof( message ) ) && rejected;
            }


            {
                // A whole header and a short payload.
                std::vector<uint8_t> corrupt( bytes.begin(), bytes.begin() + sizeof( TableBinaryHeader ) + 100 );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "truncated payload", message, sizeof( message ) ) && rejected;
            }

            {
                // A name with no terminator inside its array. Read with strcmp this
                // would run off the end of the struct.
                std::vector<uint8_t> corrupt = bytes;
                std::memset( corrupt.data() + offsetof( TableBinaryHeader, m_shapeName ), 'A', sizeof( TableBinaryHeader::m_shapeName ) );
                rejected = ExpectRejected( corrupt, table, publishedProfile.GetName(), publishedCurve, "unterminated shape name", message, sizeof( message ) ) && rejected;
            }

            passed = passed && rejected;
        }

        return passed;
    }
}
